apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    category: rbac
    deploy: prometheus
  name: sourcegraph-prometheus
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: sourcegraph-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: sourcegraph
