apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    category: rbac
    deploy: prometheus
  name: prometheus
  namespace: sourcegraph
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
