apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    category: rbac
    deploy: prometheus
  name: sourcegraph-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
