apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    category: rbac
    deploy: prometheus
  name: prometheus
  namespace: sourcegraph
roleRef:
  apiGroup: ""
  kind: Role
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: sourcegraph
