apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    deploy: prometheus
  name: prometheus
  namespace: sourcegraph
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: sourcegraph
