apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    deploy: prometheus
  name: prometheus
  namespace: sourcegraph
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: prometheus
  type: ClusterIP
