apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Serves the frontend of Sourcegraph via HTTP(S).
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: frontend
  name: sourcegraph-frontend
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sourcegraph-frontend
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sourcegraph-frontend
        deploy: sourcegraph
    spec:
      containers:
      - name: frontend
        image: 355207333203.dkr.ecr.us-west-2.amazonaws.com/sourcegraph-frontend:3.28.0-ajacobs-sourcegraph-with-chamber # TODO: replace this with non-branched image
        args:
        - serve
        env:
        - name: PGDATABASE
          value: FROM_CHAMBER
        - name: PGHOST
          value: sourcegraph.ckoaaogeaxdh.us-west-2.rds.amazonaws.com # sourcegraph-pg from terracode-tooling/stage/us-west-2/sourcegraph/rds.tf
        - name: PGPORT
          value: "5432"
        - name: PGSSLMODE
          value: require
        - name: PGUSER
          value: FROM_CHAMBER
        - name: CODEINSIGHTS_PGDATASOURCE
          value: postgres://postgres:password@codeinsights-db:5432/postgres
        - name: CODEINTEL_PGDATABASE
          value: FROM_CHAMBER
        - name: CODEINTEL_PGHOST
          value: sourcegraph-codeintel.ckoaaogeaxdh.us-west-2.rds.amazonaws.com # sourcegraph-codeintel-pg from terracode-tooling/stage/us-west-2/sourcegraph/rds.tf
        - name: CODEINTEL_PGPORT
          value: "5432"
        - name: CODEINTEL_PGSSLMODE
          value: require
        - name: CODEINTEL_PGUSER
          value: FROM_CHAMBER
        - name: SRC_GIT_SERVERS
          value: gitserver-0.gitserver:3178
        # POD_NAME is used by CACHE_DIR
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # CACHE_DIR stores larger items we cache. Majority of it is zip
        # archives of repositories at a commit.
        - name: CACHE_DIR
          value: /mnt/cache/$(POD_NAME)
        - name: GRAFANA_SERVER_URL
          value: http://grafana:30070
        - name: JAEGER_SERVER_URL
          value: http://jaeger-query:16686
        - name: PROMETHEUS_URL
          value: http://prometheus:30090
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /healthz
            port: debug
            scheme: HTTP
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: debug
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 3080
          name: http
        - containerPort: 3090
          name: http-internal
        - containerPort: 6060
          name: debug
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: "8Gi"
            memory: 4G
          requests:
            cpu: "2"
            ephemeral-storage: "4Gi"
            memory: 2G
        volumeMounts:
        - mountPath: /mnt/cache
          name: cache-ssd
      - name: jaeger-agent
        image: index.docker.io/sourcegraph/jaeger-agent:3.28.0@sha256:df843bdac4a961bc11cb3f5e963ee8894fe698f1de431906bea34a6ccc959174
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        resources:
          limits:
            cpu: "1"
            memory: 500M
          requests:
            cpu: 100m
            memory: 100M
        args:
          - --reporter.grpc.host-port=jaeger-collector:14250
          - --reporter.type=grpc
      securityContext:
        runAsUser: 0
      serviceAccountName: sourcegraph-frontend
      volumes:
      - emptyDir: {}
        name: cache-ssd
