apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Backend for indexed text search operations.
  labels:
    deploy: sourcegraph
  name: indexed-search
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: indexed-search
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: indexed-search
    spec:
      containers:
      - env:
        image: index.docker.io/sourcegraph/zoekt-webserver:2019.08.19-014a202@sha256:1f1420ed341c3f7bc3041cd46c4bf1eba97b830aeffce9640472daccb2621788
        terminationMessagePolicy: FallbackToLogsOnError
        name: zoekt-webserver
        ports:
        - containerPort: 6070
          name: http
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2G
          requests:
            cpu: 500m
            memory: 2G
        volumeMounts:
        - mountPath: /data
          name: disk
      - env:
        image: index.docker.io/sourcegraph/zoekt-indexserver:2019.08.19-014a202@sha256:3e3ff3723c96afd479177f51f25d0b4e6081281db3e6329aa3ef0a6db1759d99
        terminationMessagePolicy: FallbackToLogsOnError
        name: zoekt-indexserver
        ports:
        - containerPort: 6072
          name: index-http
        resources:
          # zoekt-indexserver is CPU bound. The more CPU you allocate to it, the
          # lower lag between a new commit and it being indexed for search.
          limits:
            cpu: "8"
            memory: 8G
          requests:
            cpu: "4"
            memory: 4G
        volumeMounts:
        - mountPath: /data
          name: disk
      securityContext:
        runAsUser: 0
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: indexed-search
