apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Backend for indexed text search operations.
  labels:
    deploy: sourcegraph
  name: indexed-search
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: indexed-search
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: indexed-search
    spec:
      containers:
      - env:
        image: index.docker.io/sourcegraph/zoekt-webserver:19-07-18_9cdf2d3@sha256:3fdbda0d32d2c74be92b7dd7d9b4d0ab7f4ebb72501d9a960521f994f942a376
        terminationMessagePolicy: FallbackToLogsOnError
        name: zoekt-webserver
        ports:
        - containerPort: 6070
          name: http
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 8G
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: disk
      - env:
        image: index.docker.io/sourcegraph/zoekt-indexserver:19-07-18_9cdf2d3@sha256:0c7c4f59281e45c54882a3f6755d4842565ed3e01b9a95e5a63efbe638b8bcec
        terminationMessagePolicy: FallbackToLogsOnError
        name: zoekt-indexserver
        ports:
        - containerPort: 6072
          name: index-http
        resources:
          # zoekt-indexserver is CPU bound. The more CPU you allocate to it, the
          # lower lag between a new commit and it being indexed for search.
          limits:
            cpu: "4"
            memory: 4G
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - mountPath: /data
          name: disk
      securityContext:
        runAsUser: 0
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: indexed-search
