apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    deploy: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.0@sha256:05838c9a9204f377987bd87645026610ba4de67c7072fae7db1a437fe4ab8974
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
