apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Handles conversion of uploaded precise code intelligence bundles.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: precise-code-intel
  name: precise-code-intel-worker
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: precise-code-intel-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: precise-code-intel-worker
    spec:
      containers:
      - name: precise-code-intel-worker
        env:
        # BEGIN EXTERNAL BLOB STORAGE CONFIGURATION
        - name: PRECISE_CODE_INTEL_UPLOAD_BACKEND
          value: S3
        - name: PRECISE_CODE_INTEL_UPLOAD_BUCKET
          value: sourcegraph-precise-code-intel-stage-usw2 # precise-code-intel-bucket from terracode-tooling/stage/us-west-2/sourcegraph/s3.tf
        - name: PRECISE_CODE_INTEL_UPLOAD_AWS_ACCESS_KEY_ID
          value: FROM_CHAMBER
        - name: PRECISE_CODE_INTEL_UPLOAD_AWS_SECRET_ACCESS_KEY
          value: FROM_CHAMBER
        - name: PRECISE_CODE_INTEL_UPLOAD_AWS_REGION
          value: us-west-2
        - name: PRECISE_CODE_INTEL_UPLOAD_AWS_ENDPOINT
          value: https://s3.$(PRECISE_CODE_INTEL_UPLOAD_AWS_REGION).amazonaws.com
        # END EXTERNAL BLOB STORAGE CONFIGURATION
        - name: NUM_WORKERS
          value: '4'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: index.docker.io/sourcegraph/precise-code-intel-worker:3.28.0@sha256:80f0ad97f81f63fca0cd062e6be7a15642f4bc187ea9280cb658dd32edd1016d
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /healthz
            port: debug
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: debug
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 3188
          name: http
        - containerPort: 6060
          name: debug
        resources:
          limits:
            cpu: "2"
            memory: 4G
          requests:
            cpu: 500m
            memory: 2G
      securityContext:
        runAsUser: 0
